In [1]:
import numpy as np

######## Create Array

In [4]:
x=np.array([56,12,35,48,71,11,28])

In [7]:
print(x)

[56 12 35 48 71 11 28]


In [5]:
type(x)

numpy.ndarray

In [6]:
print(x)

[56 12 35 48 71 11 28]


In [8]:
x.ndim

1

In [9]:
x

array([56, 12, 35, 48, 71, 11, 28])

In [10]:
x.dtype

dtype('int32')

In [15]:
x=np.array([56,12,35,48,71,11,28], dtype=np.int8)

In [16]:
x=np.array([56,12,35,48,71,11,28], dtype=np.uint8)

In [17]:
x[0]=45

In [19]:
x[0]=155

In [20]:
x

array([155,  12,  35,  48,  71,  11,  28], dtype=uint8)

In [21]:
x.size

7

In [22]:
x.shape

(7,)

In [23]:
x.sort()

In [24]:
x

array([ 11,  12,  28,  35,  48,  71, 155], dtype=uint8)

In [25]:
x.sum


<function ndarray.sum>

In [26]:
x.sum()

360

In [27]:
y=np.array([56,12,35,48.23,71,11,28])

In [28]:
y

array([56.  , 12.  , 35.  , 48.23, 71.  , 11.  , 28.  ])

In [29]:
y.dtype

dtype('float64')

In [30]:
z=np.array([56,12,35,48.23,71,11,True])

In [31]:
z

array([56.  , 12.  , 35.  , 48.23, 71.  , 11.  ,  1.  ])

In [32]:
z=np.ones(10,dtype=np.int16)
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [36]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [37]:
np.arange(0,10,.33)

array([0.  , 0.33, 0.66, 0.99, 1.32, 1.65, 1.98, 2.31, 2.64, 2.97, 3.3 ,
       3.63, 3.96, 4.29, 4.62, 4.95, 5.28, 5.61, 5.94, 6.27, 6.6 , 6.93,
       7.26, 7.59, 7.92, 8.25, 8.58, 8.91, 9.24, 9.57, 9.9 ])

In [38]:
np.linspace(1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

#############Array Operation###############

In [39]:
num1=np.array([10,20,30,40,50,60])
num2=np.array([15,25,35,45,55,65])

In [40]:
num1+10


array([20, 30, 40, 50, 60, 70])

In [41]:
num1/5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [42]:
num1*5

array([ 50, 100, 150, 200, 250, 300])

In [43]:
[10,20,30,40,50,60]*3

[10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60]

In [45]:
[10,20,30,40,50,60]*10

[10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60,
 10,
 20,
 30,
 40,
 50,
 60]

In [46]:
num1+num2

array([ 25,  45,  65,  85, 105, 125])

In [47]:
num1-num2

array([-5, -5, -5, -5, -5, -5])

In [49]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
M.ndim

2

In [52]:
M.size

9

In [53]:
M.shape

(3, 3)

In [58]:
M[1,2]

6

In [59]:
M1=M.reshape(3,3)

In [62]:
M.reshape(2,-1)


array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [61]:
M=np.array([[1,2,3],[4,5,6],[7,8,9],[7,8,9]])

In [63]:
M.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])

In [64]:
M.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 8, 9])

In [65]:
M.T

array([[1, 4, 7, 7],
       [2, 5, 8, 8],
       [3, 6, 9, 9]])

In [66]:
M.min()


1

In [67]:
M.min(axis=1)

array([1, 4, 7, 7])

In [68]:
M.min(axis=0)

array([1, 2, 3])

In [69]:
M.sum(axis=0)

array([19, 23, 27])

In [70]:
M.sum(axis=1)

array([ 6, 15, 24, 24])

In [71]:
y

array([56.  , 12.  , 35.  , 48.23, 71.  , 11.  , 28.  ])

In [72]:
q=y

In [73]:
q

array([56.  , 12.  , 35.  , 48.23, 71.  , 11.  , 28.  ])

In [74]:
q[0]=34

In [75]:
y

array([34.  , 12.  , 35.  , 48.23, 71.  , 11.  , 28.  ])

In [76]:
q=y.copy()

In [77]:
q[0]=45

In [78]:
y


array([34.  , 12.  , 35.  , 48.23, 71.  , 11.  , 28.  ])